name: Run and test

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.MD'
    branches:
      - "master"
      - "develop"
      - "ft**"
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches:
      - "master"
      - "develop"
  # To run the workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-esp32-board-3xx:
    strategy:
        matrix:
          esp-devices: [esp32, esp32s2, esp32s3]

    name: Run and test
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: Init arduino-cli.yaml config file and apply custom configs
        run: |
          # init with defaults
          arduino-cli config init

          # enable_unsafe_install to be able to install libraries via git
          arduino-cli config set library.enable_unsafe_install true

      - name: Install Board support
        run: |
          arduino-cli core update-index
          arduino-cli config add board_manager.additional_urls https://espressif.github.io/arduino-esp32/package_esp32_index.json
          arduino-cli core update-index
          arduino-cli core install esp32:esp32@3.3.2

      - name: Install libraries
        run: |
          arduino-cli lib update-index

          # common libs
          arduino-cli lib install "ArduinoJson"@7.2.1
          arduino-cli lib install "HttpClient"@2.2.0
          arduino-cli lib install "PubSubClient"@2.8.0

          # libs for all sensors
          arduino-cli lib install "TimeAlarms"@1.5.0
          arduino-cli lib install "Time"@1.6.1

          # specific libs to aquire physical measures
          arduino-cli lib install "Adafruit Unified Sensor"@1.1.14
          arduino-cli lib install "DHT sensor library"@1.4.6
          arduino-cli lib install "XENSIV Digital Pressure Sensor"@1.0.2
          arduino-cli lib install "Grove - Air quality sensor"@1.0.2
          arduino-cli lib install "Grove - Digital Light Sensor"@2.0.0

      # to get a list of FQBN you can run: `arduino-cli board listall`
      - name: Building firmwares for ${{ matrix.esp-devices }}
        run: |
          # Prepare sensor.h files based on `secrets-template`, because
          # we don't need real config files to build all firmwares in CI.
          cp secrets-template airquality-pir/secrets.h
          cp secrets-template barometer/secrets.h
          cp secrets-template dht-light/secrets.h
          cp secrets-template power-outage/secrets.h

          # build
          cd airquality-pir
          arduino-cli compile --fqbn esp32:esp32:${{ matrix.esp-devices }} ./airquality-pir.ino
          cd ..
          cd barometer
          arduino-cli compile --fqbn esp32:esp32:${{ matrix.esp-devices }} ./barometer.ino
          cd ..
          cd dht-light
          arduino-cli compile --fqbn esp32:esp32:${{ matrix.esp-devices }} ./dht-light.ino
          cd ..
          cd power-outage
          arduino-cli compile --fqbn esp32:esp32:${{ matrix.esp-devices }} ./power-outage.ino
  
  # air conditioner controllers are built with esp32 board support 2.0.17 and not 3
  build-esp32-board-2xx:
    strategy:
        matrix:
          # esp32s2 is not supported for air conditioner controllers
          # more info at https://github.com/crankyoldgit/IRremoteESP8266/issues/1922
          esp-devices: [esp32, esp32s3]

    name: Run and test
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: Init arduino-cli.yaml config file and apply custom configs
        run: |
          # init with defaults
          arduino-cli config init

          # enable_unsafe_install to be able to install libraries via git
          arduino-cli config set library.enable_unsafe_install true

      - name: Install Board support
        run: |
          arduino-cli core update-index
          arduino-cli config add board_manager.additional_urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          arduino-cli core update-index
          arduino-cli core install esp32:esp32@2.0.17

      - name: Install libraries
        run: |
          arduino-cli lib update-index

          # common libs
          arduino-cli lib install "ArduinoJson"@7.2.1
          arduino-cli lib install "HttpClient"@2.2.0
          arduino-cli lib install "PubSubClient"@2.8.0

          # specific libs for devices
          arduino-cli lib install "IRremoteESP8266"@2.8.6

      # to get a list of FQBN you can run: `arduino-cli board listall`
      - name: Building firmwares for ${{ matrix.esp-devices }}
        run: |
          # Prepare sensor.h files based on `secrets-template`, because
          # we don't need real config files to build all firmwares in CI.
          cp secrets-template ac-beko/secrets.h
          cp secrets-template ac-lg/secrets.h

          # build ac-beko
          cd ac-beko
          arduino-cli compile --fqbn esp32:esp32:${{ matrix.esp-devices }} ./ac-beko.ino
          cd ..

          # build ac-lg
          cd ac-lg
          arduino-cli compile --fqbn esp32:esp32:${{ matrix.esp-devices }} ./ac-lg.ino
          cd ..